# Application 信息
info:
  name: Eureka Server
spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
server:
  port: 8081
eureka:
# 作为客户端向服务注册
  client:
  # 是否注册在eureka
    register-with-eureka: true
    # 是否拉取注册信息
    fetch-registry: false
    service-url:
    # 默认注册中心，不设置 服务会默认想8761发送注册，会报链接失败的异常
      defaultZone: http://127.0.0.1:8081/eureka/
  server:
    # 在Eureka服务器获取不到集群里对等服务器上的实例时，需要等待的时间，单位为毫秒，默认为1000 * 60 * 5
    wait-time-in-ms-when-sync-empty: 0
    # 自我保护模式
    enable-self-preservation: false
    # 集群里eureka节点的变化信息更新的时间间隔,单位为毫秒 默认为10 * 60 * 1000
    peer-eureka-nodes-update-interval-ms: 10000
  instance:
    hostname: 127.0.0.1
    metadataMap:
          instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    ip-address: 127.0.0.1

